### ISSUE TITLE
update motivation

### ISSUE THREAD

**Issue by lachlandeer** [pp4rs/syllabus#6]
check over motivation part of syllabus to make sure the narrative is still in line with both:

1. how we fell about the state of the world
2. what we think this course is doing

**Comment by bergmul** [comment]
@lachlandeer does this refer to the introductory lecture?

**EDIT** That was stupid. I'll have a look at the syllabus.

**Comment by bergmul** [comment]
**First general thoughts:**
- I think we would stress earlier that it is not only about techniques but also tools
- Stress more that these are the absolute standard in software development (maybe use some of the examples of the introductory lecture)
- We do not address simulations as an application at all. I think we oversell the course here a bit. It's right now honestly about data work.
- We should add the motivation that these tools make collaborating easier and more efficient
- I have no idea what computational economics is. Sounds more like a method than a field like the first few.

**Comment by lachlandeer** [comment]
noted!

I'm gonna try and do some more computational / modell-y stuff this year in python with numpy/scipy and in plotting .... thinking along the lines of a Neoclassical growth model from macro or a simple dynamic monopoly / oligopoly model that I have coded up in matlab

**Comment by lachlandeer** [comment]
closed via #8
